In [44]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

env = gym.make("FrozenLake-v0")

action_space_size = env.action_space.n
state_space_size = env.observation_space.n
q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

num_episodes = 10000
max_steps_per_episodes = 100
learning_rate=0.1
discount_rate =0.99
exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001
rewards_all_episodes = []

for epsiode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episodes):
            exploration_threshold = random.uniform(0,1)
            if exploration_threshold>exploration_rate:
                action = np.argmax(q_table[state,:])
            else:
                action = env.action_space.sample()
        
            new_state,reward,done,info = env.step(action)
        
            q_table[state,action] = q_table[state,action]*(1-learning_rate) + \
                learning_rate*(reward+discount_rate*np.max(q_table[new_state,:]))
            state = new_state
            rewards_current_episode+=reward
        
            if done==True:
                break
            
    exploration_rate=min_exploration_rate+ \
            (max_exploration_rate - min_exploration_rate)*np.exp(-exploration_decay_rate*epsiode)
            
    rewards_all_episodes.append(rewards_current_episode)
rewards_per_thosand_episodes = np.array_split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("*****Avarage reward per thousand episodes*****\n")
for r in rewards_per_thosand_episodes:
    print(count,": ",str(sum(r/1000)))
    count+=1000
             
print("\n\n******Q-table******\n")
print(q_table)
            
            

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
*****Avarage reward per thousand episodes*****

1000 :  0.03400000000000002
2000 :  0.21100000000000016
3000 :  0.4230000000000003
4000 :  0.5590000000000004
5000 :  0.6460000000000005
6000 :  0.6670000000000005
7000 :  0.6870000000000005
8000 :  0.7150000000000005
9000 :  0.6660000000000005
10000 :  0.6920000000000005


******Q-table******

[[0.59652399 0.53546867 0.52421809 0.54359795]
 [0.34350783 0.26610968 0.2077119  0.52639859]
 [0.41906396 0.39402965 0.41629548 0.49872534]
 [0.35236391 0.25113926 0.31429491 0.47721381]
 [0.61288265 0.4405908  0.2598405  0.42529804]
 [0.         0.         0.         0.        ]
 [0.19028642 0.11335697 0.31416588 0.14246861]
 [0.         0.         0.         0.        ]
 [0.38443423 0.49808205 0.34631082 0.64